spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: otusBooks
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: INFO
